### ISSUE TITLE
Frontend: regex for checking if its an EAN 13 or 8

### ISSUE THREAD

**Issue by doriengr** [Onyxmoon/hsfl-master-ai-cloud-engineering#105]

**Comment by jarali** [comment]
Regex i used in another project:
`^(?:[0-9]{8}|[0-9]{13})$`
but this does not check for the checksum, it only matches if it's an 8 or 13-digit number:
https://en.wikipedia.org/wiki/International_Article_Number#Calculation_of_checksum_digit
https://barcode-coder.com/en/ean-13-specification-102.html

**Comment by Onyxmoon** [comment]
https://barcode-coder.com/en/ean-13-specification-102.html
