### ISSUE TITLE
Router for data-managment service

### ISSUE THREAD

**Issue by Onyxmoon** [Onyxmoon/hsfl-master-ai-cloud-engineering#22]

**Comment by doriengr** [comment]
@Onyxmoon Der router für data-management service haben wir beide bereits ausgebaut. Ich schließe dieses Issue fürs Erste.

**Comment by doriengr** [comment]
@Onyxmoon Der router für data-management service haben wir beide bereits ausgebaut. Ich schließe dieses Issue fürs Erste.
